# Generated by Django 5.2.10 on 2026-01-16 11:54

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(default='Capteur HealthTic', max_length=100)),
                ('device_key', models.CharField(max_length=64, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_data_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SensorData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cov_ppb', models.FloatField(help_text='COV en ppb')),
                ('eco2_ppm', models.FloatField(help_text='eCO2 en ppm')),
                ('heart_rate', models.FloatField(help_text='Fréquence cardiaque')),
                ('spo2', models.FloatField(help_text='Saturation en oxygène')),
                ('temperature', models.FloatField(help_text='Température corporelle')),
                ('ai_status', models.IntegerField(blank=True, help_text='0=Sain, 1=Infection légère, 2=Infection modérée, 3=Hypoxie sévère', null=True)),
                ('ai_status_name', models.CharField(blank=True, max_length=50, null=True)),
                ('ai_confidence', models.FloatField(blank=True, help_text="Confiance de l'IA en %", null=True)),
                ('ai_probabilities', models.JSONField(blank=True, help_text='Probabilités pour chaque classe', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('processed', models.BooleanField(default=False)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sensor_data', to='devices.device')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
