# Generated by Django 5.2.10 on 2026-01-16 00:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0003_alter_healthdata_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='healthdata',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='healthdata',
            name='air_quality',
            field=models.IntegerField(default=35, help_text="Qualité de l'air (AQI)"),
        ),
        migrations.AddField(
            model_name='healthdata',
            name='respiratory_rate',
            field=models.IntegerField(default=16, help_text='Fréquence respiratoire (/min)'),
        ),
        migrations.AddField(
            model_name='healthdata',
            name='status',
            field=models.CharField(choices=[('normal', 'Normal'), ('attention', 'Attention'), ('danger', 'Danger')], default='normal', max_length=20),
        ),
        migrations.AlterField(
            model_name='healthdata',
            name='heart_rate',
            field=models.IntegerField(help_text='Fréquence cardiaque (bpm)'),
        ),
        migrations.AlterField(
            model_name='healthdata',
            name='oxygen_level',
            field=models.FloatField(help_text='SpO2 (%)'),
        ),
        migrations.AlterField(
            model_name='healthdata',
            name='temperature',
            field=models.FloatField(help_text='Température corporelle (°C)'),
        ),
        migrations.AlterField(
            model_name='healthdata',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_data', to=settings.AUTH_USER_MODEL),
        ),
    ]
